#!/usr/bin/env python3
import os
import sys
import subprocess

def get_display_mode_name():
    output = subprocess.run(['xrandr', '-q'], stdout=subprocess.PIPE).stdout.decode('utf-8')

    final_line = ''

    for lin in output.split('\n'):
        if 'primary' in lin:
            final_line = lin
            break

    return final_line.split(' ')[0]

def display_chooser():
    modes = [
        [1024, 768,  '320p (Desktop)'],
        [1366, 768,  '480p'],
        [1600, 900,  '720p'],
        [1920, 1080,  '1080p'],
        [1920, 1080,  '1080p'],
        [2048, 1080,  '2k'],
        [3840, 2160,  '4k'],
        [7680, 4320,  '8k'],
        [15360, 8640, '16k']
    ]

    count = 1

    for mode in modes:
        print(f'{count}. {mode[0]}x{mode[1]}\t({mode[2]})')
        count = count + 1

    print("---------------------")
    inp = int(input("Choose Display: "))

    return modes[inp - 1]


def shift_screen(width, height):
    display_mode = get_display_mode_name()
    mode_name = f'{width}x{height}'
    os.system(f"gtf {width} {height} 60.0 | grep Modeline | cut -d\\\" -f3 | xargs xrandr --newmode \"{mode_name}\"")
    os.system(f'xrandr --addmode "{display_mode}" {mode_name}')
    os.system(f'xrandr --output "{display_mode}" --mode {mode_name}')

inp = input("Do you want to shift screen on your defined size: [y/N]") 

if inp in ['y', 'Y']:
    width= input("Width: ")
    height = input("Height: ")
    shift_screen(width, height)
else:
    selected = display_chooser()
    shift_screen(selected[0], selected[1])

if input('Launch VNC [Y/n]: ') in ['','y', 'Y']:
    print("Launching VNC server")
    os.system("ip a | grep inet\\ | grep 192 | xargs echo | cut -d\\/ -f1")
    os.system("x0vncserver -rfbauth ~/.vnc/passwd")

